//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersControl_V1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int volume { get; set; }
        public string unit { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
